---
- hosts: all
  name: AWS-specific roles
  become: yes
  become_method: sudo
  roles:
    - role: amazon_efs_utils
      vars:
        efs_users_gid: 2048
    - amazon_ssm_agent
    # This is for the python3-botocore task below
    - backports
    - chrony_aws
    - cloudwatch_agent
    # The instance types used for almost all the instances expose EBS
    # volumes as NVMe block devices, so that's why we need nvme here.
    - nvme
